// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkYxIC7HlQ5IGAEU23cLSk34lvMKDczY',
    appId: '1:470157246676:web:34f68e4c055cbab99e7b41',
    messagingSenderId: '470157246676',
    projectId: 'blogin-a7835',
    authDomain: 'blogin-a7835.firebaseapp.com',
    storageBucket: 'blogin-a7835.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8yKbYVz2DgDSznvJ-KKTne3nLePOT0E',
    appId: '1:470157246676:android:62ee87057a0242059e7b41',
    messagingSenderId: '470157246676',
    projectId: 'blogin-a7835',
    storageBucket: 'blogin-a7835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxluiitvc5jylsP1QI1wxTifDChx9c0xI',
    appId: '1:470157246676:ios:98c0e123f20a45929e7b41',
    messagingSenderId: '470157246676',
    projectId: 'blogin-a7835',
    storageBucket: 'blogin-a7835.appspot.com',
    iosBundleId: 'x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxluiitvc5jylsP1QI1wxTifDChx9c0xI',
    appId: '1:470157246676:ios:0e68fc7be2bc0e8a9e7b41',
    messagingSenderId: '470157246676',
    projectId: 'blogin-a7835',
    storageBucket: 'blogin-a7835.appspot.com',
    iosBundleId: 'com.example.bSell.RunnerTests',
  );
}
